FROM golang:1.20 AS build-env

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server/main.go

FROM alpine:3.14 

WORKDIR /app

COPY --from=build-env /app/server .

EXPOSE 8080

CMD ["./server"]
