FROM golang:1.20 AS build-env

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o client ./cmd/client/main.go

FROM alpine:3.14 

WORKDIR /app

COPY --from=build-env /app/client .

EXPOSE 8080

CMD ["./client", "--serverAddr=server:8080"]
